name: Rubika Bot 24/7

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install requests
      - name: Run bot
        env:
          RUBIKA_TOKEN: ${{ secrets.RUBIKA_TOKEN }}
          PROXY_URL: ${{ secrets.PROXY_URL }}   # only if needed
        run: python bot.py
